const express= require('express')
const path = require('path')
const fiex=require('./FiEx')
require('dotenv').config()
const os=require('node:os')
const dns=require('node:dns')
const bodyparser = require('body-parser')
const app = express()
const processor =require('./processor')
app.use(bodyparser.urlencoded({extended:true}))
app.use(bodyparser.json())
app.use(express.static(path.join(__dirname,'static')))

app.get('/',(req,res)=>{
    console.log(__dirname)
    res.sendFile(path.join(__dirname,'static','main','index.html'))
})
app.get('/getapps',processor.getApps)
app.get('/getapp',processor.getApp)
app.post('/login',processor.login)
app.post('/signup',processor.signup)
app.post('/savedata',processor.savedata)
app.get('/loaddata',processor.loaddata)
app.post('/initapp',processor.initapp)
app.post('/saveapp',processor.saveapp)
app.get('/loadapps',processor.loadapps)
app.post('/saveapps',processor.saveapps)

dns.lookup(os.hostname(),{'family':4},(err,addr)=>{
    app.listen(process.env.APPPORT || 2000,addr,()=>{
        console.log(`we are live on http://${addr}:${process.env.PORT}`)
    })
    fiex.fiex.listen(process.env.FPORT,addr,()=>{
        console.log(`we are live on http://${addr}:${process.env.PORT}`)
    })
})
